POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome":"Pedro Fernandes",
    "idade": 19,
    "nomeDaMae":"Edmiriam"
}
###

GET http://localhost:3333/usuarios

###

PUT http://localhost:3333/usuarios/
Content-Type: application/json

{
    "nome":"Joao da silva",
    "idade": 19,
    "nomeDaMae":"Edmiriam"
}

###

DELETE http://localhost:3333/usuarios/62ac5e5c-e458-4fd7-87ca-0ca80474aeaa