//Cria registro
POST http://localhost:3333/usuarios
Content-Type: application/json

{
    "nome":"Pedro Fernandes",
    "idade": 19,
    "nomeDaMae":"Edmiriam"
}




###
//Lista registros (com ou sem filtro[search=])
GET http://localhost:3333/usuarios?search=Pedro







###
//Atualiza registo (adicionar id no final do PUT localhost:...)
PUT http://localhost:3333/usuarios/
Content-Type: application/json

{
    "nome":"novo_nome",
    "idade":20,
    "nomeDaMae":"novo_nome_mae"
}





###
//Exclui registro
DELETE http://localhost:3333/usuarios/f48eebe3-36d0-4935-b7f5-336166466d92